# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get latest Corretto URL
      id: get-latest-corretto-url
      run: >-
        echo "::set-output name=URL::$(curl -LIs -o /dev/null -w
        %{url_effective}
        https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz)"
    - uses: actions/cache@v2
      id: corretto-cache
      name: Restore Corretto
      with:
        path: ./amazon-corretto-17-x64-linux-jdk.tar.gz
        key: >-
          ${{ runner.os }}-corretto-${{
          steps.get-latest-corretto-url.outputs.URL }}
    - name: Download AWS Corretto
      if: steps.corretto-cache.outputs.cache-hit != 'true'
      run: >-
        wget
        https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: jdkfile
        java-version: '17'
        architecture: x64
        jdkFile: ./amazon-corretto-17-x64-linux-jdk.tar.gz
    - name: Build with Maven
      run: mvn -B package --file pom.xml
